name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: 'v1.9.1+hotfix.6'
    - name: install dependencies
      run: flutter pub get
    - name: test
      run: flutter test
